[package]
name = "blake3-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"
blake3 = { version = "1.8.3", features = ["rayon"] }
wasm-bindgen-rayon = { version="1.2.1"}

[lib]
crate-type = ["cdylib", "rlib"]
